Team-Hankki/hankki-iOS

- Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
- Hankkijogbo/Hankkijogbo/.swiftlint.yml
- Hankkijogbo/Hankkijogbo/Present/Base/BaseCollectionViewCell.swift
- Hankkijogbo/Hankkijogbo/Present/Base/BaseModel.swift
- Hankkijogbo/Hankkijogbo/Present/Base/BaseTableViewCell.swift
- Hankkijogbo/Hankkijogbo/Present/Base/BaseViewController.swift
⛳️ **작업한 브랜치**
- setting/#5
👷 **작업한 내용**
- Info.plist 파일이 이동한 경로로 설정이 안 되어 있어서 설정했습니다.
- swiftlint 설치 후 규칙 몇 개 제외시켰는데 피드백 부탁드립니다.
- Base 파일 추가했습니다. 네이밍이 안 맞거나 추가/제외할 거 있으면 알려주세요!
- iOS 버전 최소 15.0으로 변경하였고 Deployment target은 17.0으로 설정했습니다.
- 모든 VC와 Cell 및 Model을 작성할 때에는 Base 파일을 상속받아서 작성해주시면 됩니다.
- Resolved: #5
> [Setting] #5 - swiftlint 및 Base 파일 세팅

- README.md
⛳️ **작업한 브랜치**
- feature/#2
👷 **작업한 내용**
라이브러리 사용 이유를 추가작성했습니다.
- Resolved: #2
> [Setting] #2 - 리드미 수정 (라이브러리 사용 이유 추가)

- Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
- Hankkijogbo/Hankkijogbo/Application/AppDelegate.swift
- Hankkijogbo/Hankkijogbo/Application/SceneDelegate.swift
- Hankkijogbo/Hankkijogbo/Global/Components/HankkiNavigationController/HankkiNavigationController.swift
- Hankkijogbo/Hankkijogbo/Global/Components/HankkiNavigationController/HankkiNavigationType.swift
- Hankkijogbo/Hankkijogbo/Global/Components/TabBar/TabBarController.swift
- Hankkijogbo/Hankkijogbo/Global/Components/TabBar/TabBarItem.swift
- TabBar Custom
- NavigationBar Custom
- TabBar 는 아직 디자인이 완성되지 않아 임의로 아이콘과 Title 넣었습니다. (TODO로 적어놨습니다.)
| GIF | ![Simulator Screen Recording - iPhone SE (3rd generation) - 2024-07-07 at 10 22 13](https://github.com/Team-Hankki/hankki-iOS/assets/101050833/d78aff78-5b6c-4676-b9f9-c8c477494ff0) | ![Simulator Screen Recording - iPhone 13 mini - 2024-07-07 at 10 23 06](https://github.com/Team-Hankki/hankki-iOS/assets/101050833/f22318a8-cc76-4815-8398-48bf0ecc778b) | ![Simulator Screen Recording - iPhone 15 - 2024-07-07 at 10 05 01](https://github.com/Team-Hankki/hankki-iOS/assets/101050833/ac4dfdb8-bc7e-4b90-ba03-a187cd23f964) |
`TabBarItem`
- 각자 View 작업 이후 ViewController 넣어주세요 …
> [Feat] #15 - Custom TabBar, NavigationBar 

- Hankkijogbo/Hankkijogbo/Present/Base/BaseCollectionViewCell.swift
- Hankkijogbo/Hankkijogbo/Present/Base/BaseTableViewCell.swift
- Hankkijogbo/Hankkijogbo/Present/Base/BaseView.swift
- Hankkijogbo/Hankkijogbo/Present/Base/BaseViewController.swift
- Base 코드에 라이브러리 추가
- Resolved: #23
> [Chore] #23 - 라이브러리 import

- Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
- Hankkijogbo/Hankkijogbo/Present/Home/Model/TotalListModel.swift
- Hankkijogbo/Hankkijogbo/Present/Home/View/TotalListBottomSheetController.swift
- Hankkijogbo/Hankkijogbo/Present/Home/View/TotalListBottomSheetView.swift
- Hankkijogbo/Hankkijogbo/Present/Home/View/TotalListCollectionViewCell.swift
- 전체 식당 리스트 BottomSheet를 구현했습니다. 
- 아이콘 확정되면 수정할 부분들이 있습니다. 
- Map 연결 후 이중 바텀시트 재검토 하겠습니다. 
- UI 작업 완료 후 바텀시트 따로 빼서 재사용하겠습니다. 
| GIF | ![Simulator Screen Recording - iPhone SE (3rd generation) - 2024-07-10 at 16 12 55](https://github.com/Team-Hankki/hankki-iOS/assets/101050833/488b37a1-262f-45b5-8d3a-8607de5362a3) | ![Simulator Screen Recording - iPhone 13 mini - 2024-07-10 at 16 11 26](https://github.com/Team-Hankki/hankki-iOS/assets/101050833/3ba4a71a-5c1d-4cc4-861f-fe55f40a6eae) | ![Simulator Screen Recording - iPhone 15 Pro - 2024-07-10 at 16 14 14](https://github.com/Team-Hankki/hankki-iOS/assets/101050833/5b52cf61-26a5-46d6-942a-9ffffa6464e1) |
- Resolved: #38
> [Feat] #38 - 전체 식당 리스트 BottomSheet

- Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
- Hankkijogbo/Hankkijogbo/Application/SceneDelegate.swift
- Hankkijogbo/Hankkijogbo/Global/Components/HankkiNavigationController/HankkiNavigationController.swift
- Hankkijogbo/Hankkijogbo/Global/Components/HankkiNavigationController/HankkiNavigationType.swift
- Hankkijogbo/Hankkijogbo/Present/Mypage/View/MypageCollectionViewCellEnum.swift
- Hankkijogbo/Hankkijogbo/Present/Mypage/View/MypageViewController.swift
- Hankkijogbo/Hankkijogbo/Present/ZipList/View/Cell/ZipListCollectionViewCell.swift
- Hankkijogbo/Hankkijogbo/Present/ZipList/View/Cell/ZipListCollectionViewCellDataStruct.swift
- Hankkijogbo/Hankkijogbo/Present/ZipList/View/Cell/ZipListViewControllerCell.swift
- Hankkijogbo/Hankkijogbo/Present/ZipList/View/ZipListViewController.swift
- 나의 족보 리스트를 볼 수 있는 뷰를 구현했습니다.
- 버튼 로직이 확실하지 않아 디자인과 협의 후 기능 추가하겠습니다.
- 이미지 에셋이 추가되면 수정 진행하겠습니다.
| GIF | <img src = "https://github.com/Team-Hankki/hankki-iOS/assets/117021241/71b4916b-57ce-45c7-9bcf-252ecf5e7f1f" width ="250"> | <img src = "https://github.com/Team-Hankki/hankki-iOS/assets/117021241/ffb127b8-e5cc-4ee3-b6b5-74e45e58e740" width ="250"> | <img src = "https://github.com/Team-Hankki/hankki-iOS/assets/117021241/95c1acc8-b705-45ed-ac26-a61fceca6bb9" width ="250"> |
- Resolved: #33
> [Feat] #33 - ZipList View Controller 

- Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
- Hankkijogbo/Hankkijogbo/Global/Components/HankkiDropDown/DropDownView.swift
- Hankkijogbo/Hankkijogbo/Network/Hankki/DTO/Response/GetPriceFilterResponseDTO.swift
- Hankkijogbo/Hankkijogbo/Network/Hankki/DTO/Response/GetSortOptionFilterResponseDTO.swift
- Hankkijogbo/Hankkijogbo/Network/Hankki/HakkiAPIService.swift
- Hankkijogbo/Hankkijogbo/Network/Hankki/HankkiTargetType.swift
- Hankkijogbo/Hankkijogbo/Present/Home/View/Cell/TypeCollectionViewCell.swift
- Hankkijogbo/Hankkijogbo/Present/Home/View/HomeViewController.swift
- Hankkijogbo/Hankkijogbo/Present/Home/ViewModel/HomeViewModel.swift
- Home 화면에서 필요한 필터링 API를 연결했습니다. 
- 종류 필터링의 이미지 부분은 dummyData 들어오는대로 이슈 파서 이미지 삽입하겠습니다. 
| <img width="219" alt="스크린샷 2024-07-17 오후 1 51 30" src="https://github.com/user-attachments/assets/2c95986b-5bfd-420c-8c53-b80425ee7037"> | <img width="230" alt="스크린샷 2024-07-17 오후 1 50 59" src="https://github.com/user-attachments/assets/c326d0b8-3a85-468c-986d-a881d05704e0"> |
`HomeViewModel `
- 필터링 정보를 가져오는 코드입니다. 
```swift
func getPriceCategoryFilterAPI(completion: @escaping (Bool) -> Void) {
NetworkService.shared.hankkiService.getPriceCategoryFilter { [weak self] result in
switch result {
case .success(let response):
self?.priceFilters = response?.data.priceCategories ?? []
completion(true)
print("SUCCESS")
case .unAuthorized, .networkFail:
completion(false)
print("FAILED") …
```
> [Network] #75 - Home 필터링 API 연결

- README.md
| GIF | <img src = "" width ="250"> | <img src = "" width ="250"> | <img src = "" width ="250"> |
`HomeView`
- 쏼라쏼라
```swift
// 코드는 이 사이에 작성하면 됩니다. 
```
- Resolved: #이슈번호
> [Docs] #70 - 

- README.md
- Readme를 수정했습니다.
- Resolved: #70
> [Docs] #70 - Readme 수정

- Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
- Hankkijogbo/Hankkijogbo.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Hankkijogbo/Hankkijogbo/Global/Components/HankkiDropDown/DropDownView.swift
- Hankkijogbo/Hankkijogbo/Global/Extensions/UIImageView+.swift
- Hankkijogbo/Hankkijogbo/Network/Hankki/DTO/Request/GetHankkiListRequestDTO.swift
- Hankkijogbo/Hankkijogbo/Network/Hankki/DTO/Response/GetCategoryFilterResponseDTO.swift
- Hankkijogbo/Hankkijogbo/Network/Hankki/DTO/Response/GetHankkiListResponseDTO.swift
- Hankkijogbo/Hankkijogbo/Network/Hankki/DTO/Response/GetPriceFilterResponseDTO.swift
- Hankkijogbo/Hankkijogbo/Network/Hankki/DTO/Response/GetSortOptionFilterResponseDTO.swift
- Hankkijogbo/Hankkijogbo/Network/Hankki/HakkiAPIService.swift
- Hankkijogbo/Hankkijogbo/Network/Hankki/HankkiTargetType.swift
- Hankkijogbo/Hankkijogbo/Present/Home/View/Cell/TypeCollectionViewCell.swift
- Hankkijogbo/Hankkijogbo/Present/Home/View/HomeViewController.swift
- Hankkijogbo/Hankkijogbo/Present/Home/ViewModel/HomeViewModel.swift
- 이미지와 관련된 API를 연동합니다. 
- 전체 식당 족보 리스트에 있는 썸네일은 BottomSheet 연결 후 data binding 하겠습니다. 
| GIF | ![Simulator Screen Recording - iPhone SE (3rd generation) - 2024-07-18 at 05 50 00](https://github.com/user-attachments/assets/92c93046-e155-4936-9665-d077046da42b) | ![Simulator Screen Recording - iPhone 13 mini - 2024-07-18 at 05 25 52](https://github.com/user-attachments/assets/bea27d35-3350-4067-9e35-3c9482e042c2) | ![Simulator Screen Recording - iPhone 15 Pro - 2024-07-18 at 05 22 05](https://github.com/user-attachments/assets/60f2f8ce-6b88-4328-8f98-eb5098057b8d) |
`TypeCollectionViewCell`, `UIImageView+`
- KingFisher 라이브러리를 사용한 이미지 변경 코드 및 적용 예시입니다. 
```swift 
extension …
```
> [Network] #84 - 이미지 API 연동 

- Hankkijogbo/Hankkijogbo/Global/Components/HankkiDropDown/DropDownView.swift
- Hankkijogbo/Hankkijogbo/Present/Home/View/Extension/FilteringButtonFunc.swift
- Hankkijogbo/Hankkijogbo/Present/Home/View/HomeViewController.swift
- Hankkijogbo/Hankkijogbo/Present/Home/View/TotalListBottomSheetView.swift
- 빌드 문제로 오류를 해결했습니다. 
- Resolved: #이슈번호
> [Fix] #93 - 오류 해결

- Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Icon/ic_pin.imageset/Contents.json
- Hankkijogbo/Hankkijogbo/Global/Resources/Assets/Assets.xcassets/Icon/ic_pin.imageset/img_pin.svg
- Hankkijogbo/Hankkijogbo/Present/Home/View/Extension/CoreLocation.swift
- Hankkijogbo/Hankkijogbo/Present/Home/View/HomeView.swift
- Hankkijogbo/Hankkijogbo/Present/Home/View/HomeViewController.swift
- 과녁 버튼 클릭 시 내 위치로 이동
- 과녁 버튼 ui 다시 잡기
- 과녁 버튼 cardView 나올 때 분기처리
- 마커 아이콘 삽입
|    구현 내용    |   img |
| :-------------: | :----------: |
| ![IMG_8541](https://github.com/user-attachments/assets/c81659d5-11d0-4b6c-b2ef-1462e80dcf44) | ![IMG_8542](https://github.com/user-attachments/assets/637b1293-e9c9-4420-99c5-0b4035cbf20c) |
- Resolved: #118
> [Fix] #118 - 위치 정보 디테일 수정

- Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
- Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/HankkiDetailViewController.swift
- Hankkijogbo/Hankkijogbo/Present/HankkiDetail/ViewModel/HankkiDetailViewModel.swift
- Hankkijogbo/Hankkijogbo/Present/HankkiList/View/HankkiListViewController.swift
- Hankkijogbo/Hankkijogbo/Present/Home/View/Cell/MarkerInfoCardView.swift
- Hankkijogbo/Hankkijogbo/Present/Home/View/TotalListBottomSheetView.swift
- Hankkijogbo/Hankkijogbo/Present/MyZip/View/MyZipListBottomSheetViewController.swift
- Hankkijogbo/Hankkijogbo/Present/Report/Complete/ReportCompleteViewController.swift
- Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/ReportViewController.swift
- Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/ViewModel/ReportViewModel.swift
- Hankki Detail로 이동을 연결 했습니다.
`ReportViewModel`
```swift
func postHankkiAPI(request: PostHankkiRequestDTO, completion: @escaping (PostHankkiResponseData) -> Void) {
let multipartData = createMultipartFormData(image: selectedImageData, request: request)
NetworkService.shared.hankkiService.postHankki(multipartData: multipartData) { result in
switch result {
case .success(let response):
guard let data = response?.data else { return }
self.getMe() { name in
if let windowScene = UIApplication.shared.connectedScenes.first as? UIWindowScene,
let rootViewController = windowScene.windows.first?.rootViewController as? UINavigationController {
let reportCompleteViewController = ReportCompleteViewController(hankkiId: Int(response?.data.id ?? 0),
reportedNumber: self.count,
nickname: name, …
```
> [Feat] #122 - Hankki Detail 이동 연결

- Hankkijogbo/Hankkijogbo/Global/Components/HankkiAlerts/AlertViewController.swift
- Hankkijogbo/Hankkijogbo/Global/Extensions/UIViewController+.swift
- Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/HankkiDetailViewController.swift
- Hankkijogbo/Hankkijogbo/Present/HankkiList/View/Cell/ZipHeaderTableView.swift
- Hankkijogbo/Hankkijogbo/Present/Home/ViewModel/HomeViewModel.swift
- Hankkijogbo/Hankkijogbo/Present/Login/View/LoginViewController.swift
- Hankkijogbo/Hankkijogbo/Present/Mypage/View/MypageCollectionViewCellEnum.swift
- Hankkijogbo/Hankkijogbo/Present/Splash/SplashViewController.swift
- Hankkijogbo/Hankkijogbo/Present/UnivSelect/ViewModel/UnivSelectViewModel.swift
|    구현 내용    |    15 pro   |
| :-------------: | :----------: |
| GIF | <img src = "https://github.com/user-attachments/assets/1440f923-a11c-4075-b01a-1d8e6c9e9e21" width ="250"> |
- Resolved: #134
> [Design] #134 - 모달 이미지 변경

- Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
- Hankkijogbo/Hankkijogbo.xcodeproj/xcshareddata/xcschemes/Hankkijogbo.xcscheme
- Hankkijogbo/Hankkijogbo/Network/Hankki/HakkiAPIService.swift
- Hankkijogbo/Hankkijogbo/Network/Hankki/HankkiTargetType.swift
- Hankkijogbo/Hankkijogbo/Present/Home/View/HomeViewController.swift
- Hankkijogbo/Hankkijogbo/Present/Home/ViewModel/HomeViewModel.swift
- GetHankkiListAPI error 해결 
- UI 수정 
- 사소한 UI 디테일 수정 
- Resolved: #132
> [Chore] #132 - 사소한 UI 디테일 수정 및 오류 해결 

- README.md
> [Docs] #131 - Readme 수정

- Hankkijogbo/Hankkijogbo/Global/Components/HankkiNavigationController/HankkiNavigationController.swift
> [Design] #123 - 헤더 폰트 수정

- Hankkijogbo/Hankkijogbo/Global/Extensions/UserDefaults+.swift
- Hankkijogbo/Hankkijogbo/Network/Auth/AuthAPIService.swift
- Hankkijogbo/Hankkijogbo/Network/Auth/AuthTargetType.swift
- Hankkijogbo/Hankkijogbo/Network/Auth/DTO/Request/AuthRequestDTO.swift
- Hankkijogbo/Hankkijogbo/Network/Zip/ZipTargetType.swift
- Hankkijogbo/Hankkijogbo/Present/HankkiList/ViewModel/HankkiListViewModel.swift
- Hankkijogbo/Hankkijogbo/Present/Login/View/LoginViewController.swift
- Hankkijogbo/Hankkijogbo/Present/Login/ViewModel/LoginViewModel.swift
- Hankkijogbo/Hankkijogbo/Present/Mypage/View/MypageViewController.swift
- Hankkijogbo/Hankkijogbo/Present/Onboarding/View/OnboardingViewController.swift
Login API의 Body Request에 identifyToken를 보내고 있었던 오류를 수정했습니다.
내 족보에서 식당 삭제 api 의 api 주소를 잘 못 요청하고 있던 오류를 수정했습니다.
회원 가입 했을 때, 아직도 이름이 안 들어가는 이슈가 생긴다면 서버 선생님들께 달려가세요.
그들은 아주 친절하게 해결해줍니다...
- Resolved: #144
> [Fix] #144 - Auth Target Type, Zip Target Type 수정

- Hankkijogbo/Hankkijogbo/Global/Extensions/UIApplication+.swift
- Hankkijogbo/Hankkijogbo/Global/Extensions/UserDefaults+.swift
- Hankkijogbo/Hankkijogbo/Network/Auth/AuthAPIService.swift
- Hankkijogbo/Hankkijogbo/Network/Base/BaseAPIService.swift
- Hankkijogbo/Hankkijogbo/Network/Base/MoyaPlugin.swift
- Hankkijogbo/Hankkijogbo/Network/Base/NetworkResult.swift
- Hankkijogbo/Hankkijogbo/Network/University/UniversityService.swift
- Hankkijogbo/Hankkijogbo/Network/User/UserAPIService.swift
- Hankkijogbo/Hankkijogbo/Network/Zip/ZipAPIService.swift
- Hankkijogbo/Hankkijogbo/Present/CreateZip/ViewModel/CreateZipViewModel.swift
- Hankkijogbo/Hankkijogbo/Present/Login/ViewModel/LoginViewModel.swift
- Hankkijogbo/Hankkijogbo/Present/Mypage/View/MypageViewController.swift
- Hankkijogbo/Hankkijogbo/Present/Mypage/ViewModel/MypageViewModel.swift
- Hankkijogbo/Hankkijogbo/Present/Splash/SplashViewController.swift
- Hankkijogbo/Hankkijogbo/Present/UnivSelect/View/UnivSelectViewController.swift
- Hankkijogbo/Hankkijogbo/Present/UnivSelect/ViewModel/UnivSelectViewModel.swift
- Hankkijogbo/Hankkijogbo/Present/ZipList/View/ZipListViewController.swift
- Hankkijogbo/Hankkijogbo/Present/ZipList/ViewModel/ZipListViewModel.swift
- Network State 분기처리를 진행했습니다.
- 변경 전 ( MypageViewModel.swift )
```swift
unc getMe() {
NetworkService.shared.userService.getMe { result in
switch result {
case .success(let response):
if let responseData = response {
self.userInfo = MypageHeaderView.DataStruct(image: responseData.data.profileImageUrl,
name: responseData.data.nickname)
} else { return }
case .unAuthorized, .pathError:
self.showAlert?("Failed")
default:
return
}
}
}
```
- 변경 후
```swift
func getMe() {
NetworkService.shared.userService.getMe { result in
result.handleNetworkResult(result) { response in
self.userInfo = MypageHeaderView.DataStruct(image: response.data.profileImageUrl,
name: response.data.nickname)
}
}
}
```
nework state 중,  state가 success 인 경우 필요한 로직만 작성해주시면 됩니다.
이외 state는 전부 공통적인 로직으로 처리해요. (다른 로직이 필요한 경우에만 분기 …
> [Refactor] #152 - Network State 분기처리 통합

- Hankkijogbo/Hankkijogbo/Present/Home/View/Extension/FilteringButtonFunc.swift
- Hankkijogbo/Hankkijogbo/Present/Home/View/HomeViewController.swift
- Hankkijogbo/Hankkijogbo/Present/Home/View/TotalListBottomSheetView.swift
- 자체적으로 QA 1차 진행
- GIF는 서버 복구 후 올리겠습니다. 
-  지도 핀 선택 후 대학 변경 시 info card view 및 지도 핀 초기화
- 홈화면 바텀시트 위로 스와이프 시, 필터링 겹치는 현상 -> 필터링 hidden 처리
- Resolved: #143
> [Fix] #143 - 자체 QA 1차 

- Hankkijogbo/Hankkijogbo/Global/Components/HankkiNavigationController/HankkiNavigationController.swift
- Hankkijogbo/Hankkijogbo/Present/Home/View/Cell/MarkerInfoCardView.swift
- Hankkijogbo/Hankkijogbo/Present/Home/View/Extension/CoreLocation.swift
- Hankkijogbo/Hankkijogbo/Present/Home/View/Extension/FilteringButtonFunc.swift
- Hankkijogbo/Hankkijogbo/Present/Home/View/HomeViewController.swift
- Hankkijogbo/Hankkijogbo/Present/Home/View/TotalListBottomSheetView.swift
- Hankkijogbo/Hankkijogbo/Present/UnivSelect/View/UnivSelectViewController.swift
- (이후 위치정보 동의시) 찾는 대학교가 없어요 우선 둘러볼게요 클릭 후 진입시 홈에서 대학교 선택란이 ‘전체’로 뜨면서 내위치가 포커싱
- BottomSheet, chip Animation duration 수정
- HomeView Navigation 대학 좌측 이동
- markCardInfoView Category Tag 변경
`TotalListBottomSheetView`
- animation 적용 (duration, options 변경)
```swift
UIView.animate(withDuration: 0.3,
delay: 0,
options: .curveEaseOut,
animations: {}
```
`HomeViewController`
- navigation 위치 변경 
```swift
navigationController.titleStackView.snp.removeConstraints()
navigationController.titleStackView.snp.makeConstraints {
$0.leading.equalToSuperview().inset(22)
$0.centerY.equalToSuperview()
}
```
`CoreLocation`
- 위치 정보 동의 시, 현재 나의 위치로 포커싱되며 NavigationBar Title은 flag를 사용해 변경한다. 
```swift
DispatchQueue.main.async {
self.rootView.mapView.moveCamera(cameraUpdate)
}
```
```swift
var …
```
> [Fix] #176 - 3차 자체 QA 

- Hankkijogbo/Hankkijogbo/Global/Components/HankkiNavigationController/HankkiNavigationController.swift
- Hankkijogbo/Hankkijogbo/Global/Components/HankkiNavigationController/HankkiNavigationType.swift
- Hankkijogbo/Hankkijogbo/Present/Home/View/HomeViewController.swift
- postion, font를 설정합니다
- Resolved: #182
> [Design] #182 - Navigation Position, Font Custom

- Hankkijogbo/Hankkijogbo/Global/Extensions/UIImageView+.swift
- Hankkijogbo/Hankkijogbo/Network/Hankki/DTO/Response/GetHankkiThumbnailResponseDTO.swift
- Hankkijogbo/Hankkijogbo/Present/Home/View/Cell/MarkerInfoCardView.swift
- Hankkijogbo/Hankkijogbo/Present/Home/View/Cell/TotalListCollectionViewCell.swift
- default 이미지 설정
- Resolved: #184
> [Design] #184 - Home Default image

- Hankkijogbo/Hankkijogbo/Network/User/DTO/Response/GetMeHankkiListResponseDTO.swift
- Hankkijogbo/Hankkijogbo/Network/Zip/Response/GetZipListResponseDTO.swift
- Hankkijogbo/Hankkijogbo/Present/HankkiList/ViewModel/HankkiListViewModel.swift
- Reported, Liked View를 수정했습니다.
- Resolved: #188
> [Fix] #188 - HankkiListViewModel Cell Model 변경

- Hankkijogbo/Hankkijogbo/Global/Components/HankkiCompositionalLayout/CompositionalLayoutFactory.swift
- Hankkijogbo/Hankkijogbo/Present/HankkiDetail/ViewModel/HankkiDetailViewModel.swift
- Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/ImageCollectionViewCell.swift
- Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/ReportCompositionalLayoutFactory.swift
- Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/ReportViewController.swift
- Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/SearchBarCollectionViewCell.swift
- Hankkijogbo/Hankkijogbo/Present/Report/Search/SearchViewModel.swift
- Hankkijogbo/Hankkijogbo/Present/Report/Search/View/SearchCollectionViewCell.swift
- Hankkijogbo/Hankkijogbo/Present/Report/Search/View/SearchViewController.swift
> [Fix] #187 - 1차 QA 반영

- Hankkijogbo/Hankkijogbo/Global/Extensions/UIViewController+.swift
- Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/HankkiDetailViewController.swift
- Hankkijogbo/Hankkijogbo/Present/HankkiDetail/ViewModel/HankkiDetailViewModel.swift
- Hankkijogbo/Hankkijogbo/Present/HankkiList/View/Cell/HankkiListTableViewCell.swift
- Hankkijogbo/Hankkijogbo/Present/HankkiList/View/HankkiListViewController.swift
- Hankkijogbo/Hankkijogbo/Present/HankkiList/ViewModel/HankkiListViewModel.swift
- Hankkijogbo/Hankkijogbo/Present/UnivSelect/View/UnivSelectViewController.swift
- README.md
- Univ Select gradient 수정
- Detail 신고 감사 알럿 nickname highlighted 기능 추가
- delete hankki api completion 수정
- detail liked list 간 하트 수 연동
- HankkiDetailViewModel.swift
```swift
/// 식당 삭제
func deleteHankkiAPI(id: Int, completion: @escaping () -> Void) {
NetworkService.shared.hankkiService.deleteHankki(id: id) { result in
result.handleNetworkResult(onSuccessVoid: completion)
}
}
```
해당 API의 경우 응답이 204로 오기 때문에, Void 값으로 decoding됩니다. 해당 경우에서는 OnSuccessVoid에 클로저를 전달해야 클로저가 실행됩니다.
- UIViewController+.swift
```swift
/// Alert을 띄우는 메서드
func showAlert(
image: UIImage? = nil,
titleText: String,
subText: String = "",
secondaryButtonText: String = "",
primaryButtonText: String,
secondaryButtonHandler: (() -> Void)? = nil,
primaryButtonHandler: (() -> Void)? = nil,
hightlightedText: String = "", …
```
> [Fix] #195 - Detail, Liked List 간 하트 수 연동

- Hankkijogbo/Hankkijogbo/Global/Extensions/UIButton+.swift
- Hankkijogbo/Hankkijogbo/Network/Hankki/DTO/Request/GetHankkiListRequestDTO.swift
- Hankkijogbo/Hankkijogbo/Network/Hankki/DTO/Request/GetHankkiPinRequestDTO.swift
- Hankkijogbo/Hankkijogbo/Network/Hankki/HakkiAPIService.swift
- Hankkijogbo/Hankkijogbo/Network/Hankki/HankkiTargetType.swift
- Hankkijogbo/Hankkijogbo/Present/Home/View/Extension/FilteringButtonFunc.swift
- Hankkijogbo/Hankkijogbo/Present/Home/View/HomeViewController.swift
- Hankkijogbo/Hankkijogbo/Present/Home/View/TotalListBottomSheetView.swift
- Hankkijogbo/Hankkijogbo/Present/Home/ViewModel/HomeViewModel.swift
- 1차 기능 QA 반영
-  Filtering Chip BottomSheet 올라왔을때 hidden
- TotalListBottomSheet Handler 영역 넗히기
- 세 개의 필터가 화면에서 겹치지 않고 하나씩 작동하는가
- 바텀시트를 아래로 내렸을 때 식당 정보들이 위로 올라오면서 내려가는가
- 위치 정보 미동의 시 -> 대학교 더 둘러볼게요 클릭 -> 시립대학교 포커싱
- 위의 사항에서 NaviBar "전체"로 변경 후 식당 모든 리스트 api 연결
- 위치 정보 동의 관련한 로직이 꼬인 것 같습니다.... 디자인 1.5차 반영 후 다시 이슈 파서 해결할게요 
- Resolved: #193
> [Fix] #193 - 1차 기능 QA 반영 

- Hankkijogbo/Hankkijogbo/Network/User/DTO/Response/GetMeResponseDTO.swift
- 바뀐 DTO를 반영했습니다.
```swift
struct GetMeResponseData: Codable {
let nickname: String
}
```
- Resolved: #204
> [Network] #204 - 바뀐 getMe DTO 반영

- Hankkijogbo/Hankkijogbo/Global/Consts/StringLiterals.swift
- Hankkijogbo/Hankkijogbo/Network/Hankki/DTO/Request/PostHankkiValidateRequestDTO.swift
- Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/HankkiDetailViewController.swift
- Hankkijogbo/Hankkijogbo/Present/Report/Search/View/SearchViewController.swift
- validate 수정된 DTO를 반영합니다
```swift
let storeName: String
```
- Resolved: #206
> [Network] #206 - validate api 수정 반영

- Hankkijogbo/Hankkijogbo/Present/Home/View/Extension/CoreLocation.swift
- Hankkijogbo/Hankkijogbo/Present/Home/View/Extension/FilteringButtonFunc.swift
- Hankkijogbo/Hankkijogbo/Present/Home/View/HomeView.swift
- Hankkijogbo/Hankkijogbo/Present/Home/View/HomeViewController.swift
- Hankkijogbo/Hankkijogbo/Present/Home/View/TotalListBottomSheetView.swift
- 1.5차 기능 QA 진행
-  상단 카테고리 필터 Button - 가격대, 정렬 2번 클릭 시 hidden
-  상단 카테고리 필터 Button 터치 영역 넓히기
-  대학교 선택 후 좌표 포커싱 Console 확인
-  TotalListBottomSheet 스크롤 영역
-  찾는 대학교가 없어요! 둘러볼게요 에서 전체가 아니라 한끼 대학교 워딩 변경
-  Target Button 사라짐 이슈
-  MarkerCardInfoView Layout 조정
`참고사항`
- 필터 선택 → 대학 선택 → 필터 초기화는 기획과 논의 후 반영하겠습니다. 
`TotalListBottomSheetView`
- BottomSheet 상태(위, 아래)에 따라 collectionView를 contentInset값을 조정합니다. 
```swift
func viewLayoutIfNeededWithUpAnimation() {
UIView.animate(withDuration: 0.3,
delay: 0,
options: .curveEaseOut,
animations: {
self.transform = .init(translationX: 0, y: -(UIScreen.getDeviceHeight() * 0.4))
}, completion: { [weak self] _ in
self?.isBottomSheetUp = true
if let collectionView = self?.totalListCollectionView {
collectionView.contentInset = .zero …
```
> [Fix] #210 - 1.5차 기능 QA 반영

- Hankkijogbo/Hankkijogbo/Global/Components/EmptyView/EmptyView.swift
- Hankkijogbo/Hankkijogbo/Global/Consts/StringLiterals.swift
- Hankkijogbo/Hankkijogbo/Global/Extensions/UIViewController+.swift
- Hankkijogbo/Hankkijogbo/Present/Home/View/Cell/TypeCollectionViewCell.swift
- Hankkijogbo/Hankkijogbo/Present/Home/View/Extension/FilteringButtonFunc.swift
- Hankkijogbo/Hankkijogbo/Present/Home/View/HomeViewController.swift
- Hankkijogbo/Hankkijogbo/Present/Onboarding/View/OnboardingViewController.swift
- Hankkijogbo/Hankkijogbo/Present/Report/Search/View/SearchViewController.swift
- 기능 버그 픽스 
- 디자인 수정사항 반영
-  대학 선택 시 필터링 초기화
-  음식 종류 필터링 - 그래픽 이미지는 48px, 그래픽과 글자 사이의 여백이 기존 8px -> 6px 로 변경
-  바텀시트 애니메이션 추가
-  emptyView Label 글자 잘림
-  온보딩 디자인 이슈
- Resolved: #212
> [Fix] #212 - 기능 버그 픽스 

- Hankkijogbo/Hankkijogbo/Global/Components/HankkiNavigationController/HankkiNavigationController.swift
- Hankkijogbo/Hankkijogbo/Present/ZipList/View/ZipListViewController.swift
- Zip List 에서 선택하지 않은 cell이 선택되는 이슈를 해결했습니다.
- navigation의 디자인을 반영했습니다.
- Resolved: #215
> [Fix] #215 - ZipList Cell 재사용성 문제 해결

- Hankkijogbo/Hankkijogbo/Present/Home/View/Extension/FilteringButtonFunc.swift
- Hankkijogbo/Hankkijogbo/Present/Home/ViewModel/HomeViewModel.swift
- 2차 QA 실시간으로 반영합니다. 
- TypeCollectionView toggle
-  [전체] 일 경우 필터링 적용
- Resolved: #218
> [Fix] #218 - 2차 QA 실시간 반영 

- Hankkijogbo/Hankkijogbo/Global/Consts/StringLiterals.swift
- Hankkijogbo/Hankkijogbo/Present/Home/View/Extension/CoreLocation.swift
- Hankkijogbo/Hankkijogbo/Present/Home/View/HomeViewController.swift
- Hankkijogbo/Hankkijogbo/Present/UnivSelect/ViewModel/UnivSelectViewModel.swift
- 2차 QA를 진행하였습니다. 
- 지도 위치 포커싱 조정
- 홈화면 지도 pin 전체 실시간 업데이트
- 홈화면 지도 줌인 default 값 정해놓기
`TotalListBottomSheetView`
- 지도 위치 포커싱 조정
```swift
let position = NMGLatLng(lat: location.coordinate.latitude - 0.0006, lng: location.coordinate.longitude)
```
`CoreLocation`, `UnivSelectViewModel`
- 홈화면 지도 pin 전체 실시간 업데이트
```swift
@objc func locationStateUpdate(_ notification: Notification) {
if let university = notification.userInfo?["university"] as? UniversityModel {
setupPosition(with: university)
}
}
```
```swift
NotificationCenter.default.addObserver(self, selector: #selector(locationStateUpdate(_:)), name: NSNotification.Name(StringLiterals.NotificationName.locationDidUpdate), object: nil)
```
`CoreLocation`
- 홈화면 지도 줌인 default 값 정해놓기
```swift
let cameraUpdate = NMFCameraUpdate(scrollTo: …
```
> [Fix] #223 - 2차 QA 

- Hankkijogbo/Hankkijogbo/Present/CreateZip/View/CreateZipViewController.swift
- Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/MenuCollectionViewCell.swift
- Hankkijogbo/Hankkijogbo/Present/Report/Search/View/SearchViewController.swift
- 아요의 마지막 자체 QA 전 사소한 수정사항을 반영했습니다.
- 제보하기 border 관련 셀 재사용 이슈 해결
- border 2 컬러 수정
- Resolved: #232
> [Fix] #232 - 마지막 자체 QA 전 사소한 수정사항 반영

- Hankkijogbo/Hankkijogbo/Present/Home/View/Extension/CoreLocation.swift
- Hankkijogbo/Hankkijogbo/Present/Home/View/HomeViewController.swift
- 3차 QA 진행
- Splash에서 home화면 초기 진입 시 현재 위치 파란 점 표출
- Resolved: #238
> [Fix] #238 - 3차 QA

- Hankkijogbo/Hankkijogbo/Global/Consts/StringLiterals.swift
- Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/HankkiDetailViewController.swift
- Hankkijogbo/Hankkijogbo/Present/HankkiDetail/ViewModel/HankkiDetailViewModel.swift
- Hankkijogbo/Hankkijogbo/Present/HankkiList/View/HankkiListViewController.swift
- alert dismiss 수정
- Hankki List Will appear 수정
- Resolved: #236
> [Fix] #236 - 릴리즈 전 마지막 QA 반영

- Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/MenuCollectionViewCell.swift
- Hankkijogbo/Hankkijogbo/Present/Report/ReportMain/View/ReportViewController.swift
- 이미지 첨부 시 로딩뷰 뜨는 타이밍 수정
- 제보 가격 border 색 변경
- Resolved: #237
> [Fix] #237 - 릴리즈 전 자체 QA 반영

- Hankkijogbo/Hankkijogbo/Present/Home/View/HomeView.swift
- Hankkijogbo/Hankkijogbo/Present/Home/View/HomeViewController.swift
> [Feat] #267 - 둘러보기 로그인 유도 Alert 구현

- Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
- Hankkijogbo/Hankkijogbo/Global/Extensions/UIApplication+.swift
- Hankkijogbo/Hankkijogbo/Network/Base/NetworkResult.swift
- Hankkijogbo/Hankkijogbo/Network/Base/NetworkResultDelegate.swift
- Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/HankkiDetailViewController.swift
- Hankkijogbo/Hankkijogbo/Present/HankkiDetail/ViewModel/HankkiDetailViewModel.swift
- Hankkijogbo/Hankkijogbo/Present/HankkiList/View/HankkiListViewController.swift
- Hankkijogbo/Hankkijogbo/Present/HankkiList/ViewModel/HankkiListViewModel.swift
- Hankkijogbo/Hankkijogbo/Present/Home/View/HomeViewController.swift
- Hankkijogbo/Hankkijogbo/Present/Home/ViewModel/HomeViewModel.swift
- Hankkijogbo/Hankkijogbo/Present/UnivSelect/View/UnivSelectViewController.swift
- Hankkijogbo/Hankkijogbo/Present/UnivSelect/ViewModel/UnivSelectViewModel.swift
- Hankkijogbo/Hankkijogbo/Present/ZipList/View/ZipListViewController.swift
- Hankkijogbo/Hankkijogbo/Present/ZipList/ViewModel/ZipListViewModel.swift
- 둘러보기 기능을 추가합니다. 
- Resolved: #274
> [Feat] #274 - 둘러보기 기능 추가 

- Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
- Hankkijogbo/Hankkijogbo/Global/Supporting Files/Info.plist
- Hankkijogbo/Hankkijogbo/Present/UnivSelect/View/UnivSelectViewController.swift
- 시립대 Id 변경
- 앱이름 변경
- 버전 업데이트 
- Resolved: #276
> [Hotfix] #276 - universityId, display name 변경 

- Hankkijogbo/Hankkijogbo/Global/Components/HankkiNavigationController/HankkiNavigationController.swift
- Hankkijogbo/Hankkijogbo/Global/Components/TabBar/TabBarController.swift
- Hankkijogbo/Hankkijogbo/Global/Consts/StringLiterals.swift
- Hankkijogbo/Hankkijogbo/Global/Extensions/UIButton+.swift
- Hankkijogbo/Hankkijogbo/Present/Home/View/HomeView.swift
- Hankkijogbo/Hankkijogbo/Present/Home/View/HomeViewController.swift
- Hankkijogbo/Hankkijogbo/Present/Home/View/TotalListBottomSheetView.swift
- 2차 스프린트 디자인 QA 반영함 
- 홈 네비바 leading 값 필터칩이랑 똑같게
- 홈 필터칩 텍스트 변경
- 홈 필터칩 그림자
- 홈 필터칩 셀렉 - 취소 후 text color 연함
- 타겟버튼 살짝 오른쪽으로 이동
- 탭바 아이콘, 텍스트 간격 0으로
- Resolved: #278
> [Fix] #278 - 2차 스프린트 디자인 QA

- Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
- Hankkijogbo/Hankkijogbo/Global/Components/HankkiDropDown/DropDownView.swift
- Hankkijogbo/Hankkijogbo/Global/Consts/StringLiterals.swift
- Hankkijogbo/Hankkijogbo/Network/Hankki/DTO/Response/GetPriceFilterResponseDTO.swift
- Hankkijogbo/Hankkijogbo/Present/Home/View/FilteringBottomSheetViewController.swift
- Hankkijogbo/Hankkijogbo/Present/Home/View/HomeViewController.swift
- Hankkijogbo/Hankkijogbo/Present/UnivSelect/ViewModel/UnivSelectViewModel.swift
- 필터링 바텀시트 구현 
- 아직 서버 업뎃 안됨 
- 뷰연결 안함
- 나중에 여유되면 collectionview cell들로 바꾸겠어요^_^ 일단 스프린트 기간 상 pr 먼저 올립니다 
`FilteringBottomSheetViewController`
- filtering button style 메소드 관리 
```swift
func defaultButtonStyle(button: UIButton) {
button.do {
$0.makeRoundBorder(cornerRadius: 16, borderWidth: 1, borderColor: .gray300)
$0.titleLabel?.font = .setupPretendardStyle(of: .caption1)
$0.setTitleColor(.gray600, for: .normal)
$0.contentEdgeInsets = UIEdgeInsets(top: 6, left: 12, bottom: 6, right: 12)
$0.sizeToFit()
}
}
func selectedButtonStyle(button: UIButton) {
button.do {
$0.makeRoundBorder(cornerRadius: 16, borderWidth: 1, borderColor: .red500)
$0.titleLabel?.font = .setupPretendardStyle(of: .caption1)
$0.setTitleColor(.red500, for: .selected)
$0.backgroundColor = .red100
$0.contentEdgeInsets = …
```
> [Feat] #310 - Filtering Bottom Sheet 

- Hankkijogbo/Hankkijogbo.xcodeproj/project.pbxproj
- Hankkijogbo/Hankkijogbo/Global/Components/HankkiLineView/CustomLineView.swift
- Hankkijogbo/Hankkijogbo/Present/Home/View/Extension/FilteringButtonFunc.swift
- Hankkijogbo/Hankkijogbo/Present/Home/View/FilteringBottomSheetViewController.swift
- Hankkijogbo/Hankkijogbo/Present/Home/View/HomeView.swift
- Hankkijogbo/Hankkijogbo/Present/Home/View/HomeViewController.swift
- Hankkijogbo/Hankkijogbo/Present/Home/View/TotalListBottomSheetView.swift
- 나멈지 작업했어요 
- 플로팅 버튼 bottomsheet 연결
- bottomsheet layout
- bottomsheet dim 분기처리
- filtering chip select, normal
- 아직 mapview, hankkiList에 필터링(가격, 정렬) 업데이트 되지 않음... 
- category 설정 후(한식, 양식 등) bottomsheet filtering 선택하면 category가 유지되지 않음 (아예 api 요청에서 리셋됨) 
`CustomLineView`
- 색상과 높이를 동적으로 설정할 수 있는 Custom Line View입니다. (default는 gray200, height 1)
```swift
final class CustomLineView: UIView {
init(frame: CGRect = .zero, backgroundColor: UIColor = .gray200, height: Int = 1) {
super.init(frame: frame)
setupStyle(backgroundColor: backgroundColor)
setupLayout(height: height)
}
required init?(coder: NSCoder) {
super.init(coder: coder)
setupStyle(backgroundColor: .gray200)
setupLayout(height: 1)
}
override var intrinsicContentSize: CGSize {
return CGSize(width: UIView.noIntrinsicMetric, height: 1) …
```
> [Feat] #315 - Home Filtering BottomSheet 연결

- Hankkijogbo/Hankkijogbo/Present/HankkiList/View/BaseHankkiListViewController.swift
- Hankkijogbo/Hankkijogbo/Present/HankkiList/View/HankkiListViewController.swift
Hankki List 를 수정하면서 Hankki Detail과 충돌 났던 부분을 고쳤습니다
컨플릭트 해결하다가 놓친것같네요.. .미안합니다
- Resolved: #325
> [Fix] #325 - HankkiList내 HankkiDetail 생성자 변경사항 반영

- Hankkijogbo/Hankkijogbo/Present/HankkiDetail/View/DifferentInfoView.swift
- Hankkijogbo/Hankkijogbo/Present/HankkiList/View/BaseHankkiListViewController.swift
- 3차 스프린트 식당 상세 QA를 반영했습니다.
- 내 족보 > 식당 상세 > 식당 삭제 시 주황색 네비바인 이슈 해결
- 아이콘 크기 변경
- Legend Easy 누워서 떡 먹기핑
- Resolved: #332
> [Fix] #332 - 3차 스프린트 식당 상세 QA 반영
